extends TileMapLayer
class_name Earth

enum TILE {
	DIRT1,
	DIRT2,
	DIRT3,
	DIRT4,
	DIRT5,
	IRONIUM,
	BRONZIUM,
	SILVERIUM,
	GOLDIUM,
	PLATINIUM,
	EINSTEINIUM,
	EMERALD,
	RUBY,
	DIAMOND,
	AMAZONITE,
	DINOSAUR_BONES,
	TREASURE,
	MARTIAN_SKELETON,
	RELIGIOUS_ARTIFACT,
	BLUEPRINT,
	ROCK1,
	ROCK2,
	ROCK3,
	LAVA1,
	LAVA2,
	LAVA3,
	PAVEMENT,
	PAVEMENT_RIGHT,
	PAVEMENT_LEFT,
	GRASS1,
	GRASS2,
	CAVE1,
	CAVE2,
	CAVE3,
	CAVE4,
	CAVE5,
	CAVE6,
	CAVE7,
	CAVE8,
	CAVE9,
	CAVE10,
	CAVE11,
	CAVE12,
	CAVE13,
	HELL_ROOF1,
	HELL_ROOF2,
	HELL_FLOOR1,
	HELL_FLOOR2,
	BLACK,
	HALF_DUG
}

const SOURCE_ID = 0
const TILE_ATLAS = {
	TILE.DIRT1 : Vector2i(0,0),
	TILE.DIRT2 : Vector2i(0,1),
	TILE.DIRT3 : Vector2i(0,2),
	TILE.DIRT4 : Vector2i(0,3),
	TILE.DIRT5 : Vector2i(0,4),
	
	TILE.IRONIUM : Vector2i(1,0),
	TILE.BRONZIUM : Vector2i(1,1),
	TILE.SILVERIUM : Vector2i(1,2),
	TILE.GOLDIUM : Vector2i(1,3),
	TILE.PLATINIUM : Vector2i(1,4),
	TILE.EINSTEINIUM : Vector2i(1,5),
	TILE.EMERALD : Vector2i(1,6),
	TILE.RUBY : Vector2i(1,7),
	TILE.DIAMOND : Vector2i(1,8),
	TILE.AMAZONITE : Vector2i(1,9),
	
	TILE.DINOSAUR_BONES : Vector2i(2,0),
	TILE.TREASURE : Vector2i(2,1),
	TILE.MARTIAN_SKELETON : Vector2i(2,2),
	TILE.RELIGIOUS_ARTIFACT : Vector2i(2,3),
	TILE.BLUEPRINT : Vector2i(2,4),
	
	TILE.ROCK1 : Vector2i(3,0),
	TILE.ROCK2 : Vector2i(3,1),
	TILE.ROCK3 : Vector2i(3,2),
	
	TILE.LAVA1 : Vector2i(4,0),
	TILE.LAVA2 : Vector2i(4,1),
	TILE.LAVA3 : Vector2i(4,2),
	
	TILE.PAVEMENT : Vector2i(5,0),
	TILE.PAVEMENT_RIGHT : Vector2i(5,1),
	TILE.PAVEMENT_LEFT : Vector2i(5,2),
	TILE.GRASS1 : Vector2i(5,3),
	TILE.GRASS2 : Vector2i(5,4),
	
	TILE.CAVE1 : Vector2i(6,0),
	TILE.CAVE2 : Vector2i(6,1),
	TILE.CAVE3 : Vector2i(6,2),
	TILE.CAVE4 : Vector2i(6,3),
	TILE.CAVE5 : Vector2i(6,4),
	TILE.CAVE6 : Vector2i(6,5),
	TILE.CAVE7 : Vector2i(6,6),
	TILE.CAVE8 : Vector2i(6,7),
	TILE.CAVE9 : Vector2i(6,8),
	TILE.CAVE10 : Vector2i(6,9),
	TILE.CAVE11 : Vector2i(6,10),
	TILE.CAVE12 : Vector2i(6,11),
	TILE.CAVE13 : Vector2i(6,12),
	
	TILE.HELL_ROOF1 : Vector2i(7,0),
	TILE.HELL_ROOF2 : Vector2i(7,1),
	TILE.HELL_FLOOR1 : Vector2i(7,2),
	TILE.HELL_FLOOR2 : Vector2i(7,3),
	TILE.BLACK : Vector2i(7,4),
	
	TILE.HALF_DUG : Vector2i(8,0)
}



func set_tile(cell: Vector2i, tile: TILE) -> void:
	set_cell(cell, SOURCE_ID, TILE_ATLAS[tile])
